package scanner;

public enum TokenType {
    KEYWORD, 
    ID, 
    OPERATOR,
    OPERATOR_ARITHMETIC,
    OPERATOR_LOGICAL,
    OPERATOR_RELATIONAL,
    OPERATOR_BITWISE,
    LITERAL_INT,
    LITERAL_STR,
    INTEGER_LITERAL,
    LITERAL_CHAR,
    LITERAL_BINARY, 
    LITERAL_OCTAL,  
    LITERAL_HEX,
    LITERAL_DOUBLE;
}
